stages:
  - ci
  - deploy
  - rm

variables:
  IMG_NAME: sdk-ngultra
  REG_HOST: docker-registry:443/embedded
  SDK_NGULTRA_DIR: /locod/docker/nx/sdk/ngultra/

build-ci-docker:
  stage: ci
  tags: [docker-build, VM]

  script:
    - docker build -t ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} -f Dockerfile ${SDK_NGULTRA_DIR}
    - docker run --rm -t ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} bash -c 'arm-none-eabi-gcc'

build-deploy:
  stage: deploy
  tags: [docker-build, VM]
  
  only:
    - tags

  script:
    - docker tag ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG 
    - docker image tag ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG ${REG_HOST}/${IMG_NAME}:latest
    - docker push ${REG_HOST}/${IMG_NAME}:latest
    - docker push ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG

remove-tmp-img:
  stage: rm
  tags: [docker-build, VM]

  script:
    - docker image rm ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME}
